networks:
  synchronizer-nw:
services:
  vkservice:
    container_name: vkservice
    image: vkservice
    build:
      context: .
      dockerfile: VK.Music.Service/Dockerfile
    ports:
      - "8081:8020"
    networks: 
      - synchronizer-nw
  yandexservice:
    container_name: yandexservice
    image: yandexservice
    build:
      context: .
      dockerfile: Yandex.Music.Service/Dockerfile
    ports:
      - "8082:8030"
    networks: 
      - synchronizer-nw
  synchronizer:
    container_name: synchronizer
    image: synchronizer
    build:
      context: .
      dockerfile: Synchronizer.WebApp/Dockerfile
    environment:
      - vkserviceUrl=http://vkservice
      - yandexserviceUrl=http://yandexservice
    ports:
      - "8080:80"
    stdin_open: true
    networks: 
      - synchronizer-nw
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Synchronizer
    ports:
      - "5432:5432"
    networks:
      - synchronizer-nw
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: