networks:
  synchronizer-nw:
services:
  vk-service:
    container_name: vk-service
    image: vk-service
    build:
      context: .
      dockerfile: VK.Music.Service/Dockerfile
    ports:
      - "8081:8020"
    networks: 
      - synchronizer-nw
  yandex-service:
    container_name: yandex-service
    image: yandex-service
    build:
      context: .
      dockerfile: Yandex.Music.Service/Dockerfile
    ports:
      - "8082:8030"
    networks: 
      - synchronizer-nw
  synchronizer-service:
    container_name: synchronizer-service
    image: synchronizer-service
    build:
      context: .
      dockerfile: Synchronizer.Service/Dockerfile
    environment:
      - vkServiceUrl=http://vk-service
      - yandexServiceUrl=http://yandex-service
    ports:
      - "8083:80"
    stdin_open: true
    networks: 
      - synchronizer-nw
    depends_on: 
      - postgres
  synchronizer-web:
    container_name: synchronizer-web
    image: synchronizer-web
    build:
      context: .
      dockerfile: Synchronizer.WebApp/Dockerfile
    environment:
      - vkServiceUrl=http://vk-service
      - yandexServiceUrl=http://yandex-service
      - synchronizerServiceUrl=http://synchronizer-service
    ports:
      - "8080:80"
    stdin_open: true
    networks: 
      - synchronizer-nw
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Synchronizer
    ports:
      - "5432:5432"
    networks:
      - synchronizer-nw
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: